name: forex-backtester

startup_window: shell

windows:
  - shell:
  - claude:
      - alias run="tmux rename-window -t\${TMUX_PANE} 'claude'; clear; claude --dangerously-skip-permissions; tmux rename-window -t\${TMUX_PANE} '🔴 claude'"
      - run