name: forex-backtester

startup_window: shell

on_project_start:
  - git stash
  - git pull
  - git stash pop

windows:
  - editor:
      - alias run="nvim ."
      - nvim .
  - shell:
  - claude:
      - alias run="claude --dangerously-skip-permissions"
      - claude --dangerously-skip-permissions
  - git: tig
  - webserver:
      - alias run="make watch"
      - make watch
